=begin pod

=TITLE class X::Obsolete

=SUBTITLE Compilation error due to use of obsolete syntax

    class X::Obsolete does X::Comp { }

Syntax error thrown when obsolete (mostly Perl 5) syntax is detected.

For example

    m/abc/i

dies with

    ===SORRY!===
    Unsupported use of /i; in Perl 6 please use :i

=head1 Methods

=head2 method old

    method old() returns Str:D

Returns a textual description of the obsolete syntax construct

=head2 method replacement

    method replacement() returns Str:D

Describes what to use instead of the obsolete syntax.

=head2 method when

    method when() returns Str:D

Returns a string describing the state of the language (usually
C<" in Perl 6">).

=end pod
