=begin pod

=TITLE Modules and Tools related to module developpment

=SUBTITLE What can help you write/test/improve your module(s)

Here is a list of modules that you can find on Perl 6 ecosystem
that aims to make the experiences of developping Perl 6 modules
more fun.

=head1 Modules builder and Authoring tools

Here some modules/tools that can help you with generating files that are part
of a module.

=item L<App::Mi6|http://modules.perl6.org/dist/App::Mi6>     Minimal authoring tool for Perl6


=head1 Tests

Some tests related modules


=item L<Test::META|http://modules.perl6.org/dist/Test::META>      Test your META6.info file
=item L<Test::Output|http://modules.perl6.org/dist/Test::Output>  Test the output to STDOUT and STDERR your program generates


=head1 NativeCall

Here some modules to help you work with NativeCall.


=item L<NativeHelpers::Array|http://modules.perl6.org/dist/NativeHelpers::Array>  Provides routines to deal with CArray
=item L<App::GPTrixie|http://modules.perl6.org/dist/App::GPTrixie>                Generate NativeCall code from C headers file
=item L<NativeCall::TypeDiag|http://modules.perl6.org/dist/NativeCall::TypeDiag>  Provides routines to test your CStruct


=end pod