=begin pod

=TITLE Unicode versus Texas symbols

=SUBTITLE Unicode symbols and their Texas (ASCII) counterparts

The following unicode symbols can be used in Perl 6 without needing to load
any additional modules.  Please note that the Since column applies to the
version of Perl the symbol was known to be available.  It is only mentioned
if it is different from C<6.c>.

=head1 Alphabetic Characters

Please note that any codepoints that have the C<Ll> or C<Lu> property,
can be used just like any other alphabetic character from the ASCII range,
like "A" or "a".

=head1 Numeric characters

Any codepoint that has the L<Nd> property, can be used as a digit in any
number, unless special cased in the list below.

=head1 Whitespace characters

Besides spaces and tabs you can use any other unicode whitespace character
that has the L<Zs>, L<Zl> or L<Zp> property.

=head1 Numeric values

Any codepoint that has the L<No> property, can be used as a numeric value,
such as ½ and ⅓.

=head1 Other acceptable codepoints

This list contains the codepoints (and their Texas (ASCII) equivalents) that
have a special meaning in Perl 6.

=begin table
  symbol   codepoint   Texas       Since   Remarks
  ------   ---------   ---------   -----   ---------------------------------
  «        U+00AB      <<                  as part of «» or .«

  »        U+00BB      >>                  as part of «» or .»

  ×        U+00D7      *

  ÷        U+00F7      /

  −        U+2212      -

  ∘        U+2218      o

  ≅        U+2245      =~=

  π        U+03C0      pi                  3.14159_26535_89793_238e0

  τ        U+03C4      tau                 6.28318_53071_79586_476e0

  𝑒        U+1D452     e                   2.71828_18284_59045_235e0

  ∞        U+221E      Inf

  …        U+2026      ...

  ‘        U+2018      '                   as part of ‘’ or ‚’ or ’‘

  ’        U+2019      '                   as part of ’‘ or ’’

  ‚        U+201A      '                   as part of ‚‘ or ‚’

  “        U+201C      "                   as part of “” or „” or ”“

  ”        U+201D      "                   as part of ”“ or ””

  „        U+201E      "                   as part of „“ or „”

  ｢        U+FF62      Q//                 as part of ｢｣

  ｣        U+FF63      Q//                 as part of ｢｣

  ¯        U+00AF      N/A                 as part of exponentiation

  ⁺        U+207A      N/A                 as part of exponentiation

  ⁻        U+207B      N/A                 as part of exponentiation

  ⁰        U+2070      **0                 can be combined with ⁰..⁹

  ¹        U+2071      **1                 can be combined with ⁰..⁹

  ²        U+2072      **2                 can be combined with ⁰..⁹

  ³        U+2073      **3                 can be combined with ⁰..⁹

  ⁴        U+2074      **4                 can be combined with ⁰..⁹

  ⁵        U+2075      **5                 can be combined with ⁰..⁹

  ⁶        U+2076      **6                 can be combined with ⁰..⁹

  ⁷        U+2077      **7                 can be combined with ⁰..⁹

  ⁸        U+2078      **8                 can be combined with ⁰..⁹

  ⁹        U+2079      **9                 can be combined with ⁰..⁹

  ∅        U+2205      set()

  ∈        U+2208      (elem)

  ∉        U+2209      !(elem)

  ∋        U+220B      (cont)

  ∌        U+220C      !(cont)

  ⊆        U+2286      (<=)

  ⊈        U+2288      !(<=)

  ⊂        U+2282      (<)

  ⊄        U+2284      !(<)

  ⊇        U+2287      (>=)

  ⊉        U+2289      !(>=)

  ⊃        U+2283      (>)

  ⊅        U+2285      !(>)

  ≼        U+227C      (<+)

  ≽        U+227D      (>+)

  ∪        U+222A      (|)

  ∩        U+2229      (&)

  ∖        U+2216      (-)

  ⊖        U+2296      (^)

  ⊍        U+228D      (.)

  ⊎        U+228E      (+)
=end table

=end pod
