=begin pod

=TITLE role Baggy

=SUBTITLE Collection of distinct weighted objects

    class Baggy does QuantHash { }

A role for collections of weighted objects. See L<Bag>, L<BagHash>, and
L<Mixy>.

=head1 Methods

=head2 method grab

=comment TODO

=head2 method grabpairs

=comment TODO

=head2 method pick

=comment TODO

=head2 method pickpairs

=comment TODO

=head2 method roll

=comment TODO

=head2 method classify-list

=comment TODO

=head2 method categorize-list

=comment TODO

=head2 method keys

=comment TODO

=head2 method values

=comment TODO

=head2 method kv

=comment TODO

=head2 method elems

=comment TODO

=head2 method total

=comment TODO

=head2 method ACCEPTS

=comment TODO

=head1 See Also

L<Sets, Bags, and Mixes|/language/setbagmix>

=end pod
