=begin pod

=TITLE enum Order

=SUBTITLE Human readable form for comparison operators.

    enum Order (:Less(-1), :Same(0), :More(1)); 

=head1 Operators

=head2 infix cmp 

	multi sub infix:<cmp>(\a, \b) returns Order:D

Coerces it's arguments to Stringy.

=head2 infix <=>

   multi sub infix:«<=>»(Int:D \a, Int:D \b) returns Order:D

Specialized form for Int.

=end pod
