=begin pod

=TITLE class X::Does::TypeObject

=SUBTITLE Error thrown when trying to mix into a type object

    class X::Does::TypeObject is Exception { ... }

When you try to add one or more roles to a type object with C<does> after it
has been composed, an error of type C<X::Does::TypeObject> is thrown:

    Mu does Numeric;    # Cannot use 'does' operator with a type object.

The correct way to applies roles to type objects is at declaration time:

    class GrassmannNumber does Numeric { ... }

=head1 Methods

=head2 method type

    method type(X::Codes::TypeObject:D:) returns Mu:U

Returns the type object into which the code tried to mix in a role.

=end pod
