=begin pod

=TITLE role Metamodel::AttributeContainer

=SUBTITLE Meta role for holding attributes

    role Metamodel::AttributeContainer { ... }

Classes, roles and grammars can have attributes. Storage and introspection of
attributes is implemented by this role.

=head1 Methods

=head2 method add_attribute

    method add_attribute(Metamodel::AttributeContainer: $obj, $name, $attribute)

Adds an attribute. C<$attribute> must be an object that supports the
methods C<name>,  C<type> and C<package>, which are called without arguments.
It can for example be of L<type Attribute|/type/Attribute>.

=head2 method attributes

    method attributes(Metamodel::AttributeContainer: $obj)

Returns a list of attributes. For most Perl 6 types, these will be objects of
L<type Attribute|/type/Attribute>.

=begin comment

TODO: compose_attributes, set_rw, rw, get_attribute_for_usage

Also TODO: desribe :local, :excl, :all options of method attributes

=end comment

=end pod
