=begin pod

=TITLE role Metamodel::C3MRO

=SUBTITLE Metamodel role for the C3 method resolution order

    role Metamodel::C3MRO { }

L<Meta model|/language/mop> role for the I<C3> method resolution order (MRO).

=head1 METHODS

=head2 compute_mro

    method compute_mro($type)

Computes the method resolution order.

=head2 mro

    method mro($type)

Returns a list of types in the method resolution order.

    say Int.^mro    # (Int) (Cool) (Any) (Mu)

Returns a list of types in the method resolution order, even those that are
marked C<is hidden>.

=head2 mro_unhidden

    method mro_unhidden($type)

Returns a list of types in method resolution order, excluding those that are
marked with C<is hidden>.

=end pod
