=begin pod

=TITLE role X::Proc::Async

=SUBTITLE Exception thrown by L<Proc::Async>.

    role X::Proc::Async is Exception { ... }

All exceptions thrown by L<Proc::Async> do this common role.

=head1 Methods

=head2 method proc

    method fproc(X::Proc::Async:D) returns Proc::Async

Returns the object that threw the exception.

=end pod
