=begin pod

=TITLE class Bag

    class Bag does Baggy { }

An immutable collection of weighted values. These weights are always
integers, and can be accessed with the C<{ }> postcircumfix. For a
mutable collection of weighted values, see L<BagHash>.

    bag('a', 'b', 'c', 'a', 'd', 'a')<a> == 3

=head1 Operators

=head2 bag

    sub bag(*@args --> Bag)

Creates a new C<Bag> from C<@args>.

=head2 infix:<(|)>

    only sub infix:<(|)>(**@p)

=head2 infix:<∪>

    only sub infix:<<"\x222A">>(|p)

=head2 infix:<(&)>

    only sub infix:<(&)>(**@p)

=head2 infix:<∩>

    only sub infix:<<"\x2229">>(|p)

=head2 infix:<(-)>

    only sub infix:<(-)>(**@p)

=head2 infix:<∖>

    only sub infix:<<"\x2216">>(|p)

=head2 infix:<(.)>

    only sub infix:<(.)>(**@p)

=head2 infix:<⊍>

    only sub infix:<<"\x228D">>(|p)

=head2 infix:<(+)>

    only sub infix:<(+)>(**@p)

=head2 infix:<⊎>

    only sub infix:<<"\x228E">>(|p)

=head2 infix:<(<+)>

    multi sub infix:<<(<+)>>(Any $a, Any $b --> Bool)
    multi sub infix:<<(<+)>>(Baggy $a, Baggy $b --> Bool)

=head2 infix:<≼>

    only sub infix:<<"\x227C">>($a, $b --> Bool)

=head2 infix:<(>+)>

    multi sub infix:<<(>+)>>(Baggy $a, Baggy $b --> Bool)
    multi sub infix:<<(>+)>>(Any $a, Any $b --> Bool)

=head2 infix:<≽>

    only sub infix:<<"\x227D">>($a, $b --> Bool)

=end pod
