=begin pod

=head1 Bool

    enum Bool <False True>

An enum for boolean true/false decisions

=head2 Operators

=head3 prefix:<?>

    multi sub prefix:<?>(Mu) returns Bool:D

Coerces its argument to C<Bool>.

=head3 prefix:<so>

    multi sub prefix:<so>(Mu) returns Bool:D

Coerces its argument to C<Bool>, has looser precedence than C<< prefix:<?> >>.

=end pod
