=begin pod

=head1 Buf

    class Buf does Positional { ... }

A C<Buf> (short for buffer) is a binary string, and generally returned from
low-level IO operations. In the abstract it is just a list of integers, so
for example indexing into a C<Buf> with C<.[$idx]> returns an C<Int>.

=head2 Methods

=head3 new

    method new(*@codes)

Creates a C<Buf> from a list of integers.

=head3  Bool

    multi method Bool(Buf:D:)

Returns C<False> if and only if the buffer is empty.

=head3 elems

    multi method elems(Buf:D:) returns Int:D

Returns the number of elements of the buffer.

=end pod
