=begin pod

=TITLE class Int

    class Int is Cool does Real { ... }

C<Int> objects store integral numbers of arbitrary size. C<Int>s are immutable.

=head1 Methods

=head2 Bool

    multi method Bool() returns Str

Returns C<False> if integer is 0, C<True> otherwise.

=head2 Int

    multi method Int() returns Int

Returns itself.

=head2 FatRat

    multi method FatRat() returns FatRat

Converts integer to C<FatRat>.

=head2 Str

    multi method Str() returns Str

Returns string representation of integer.

=head2 gist

    multi method gist() returns Str

Returns string representation of integer.

=head2 perl

    multi method perl() returns Str

Returns string representation of integer.

=head1 Operators

=head2 div

    multi sub infix:<div>(Int:D, Int:D) returns Int:D

Does an integer division, rounded down.

=end pod
