=begin pod

=TITLE class IO

   class IO::Path is Cool does IO::FileTestable { }

=head1 Methods

=head2 dir

    sub dir Cool $path = '.', Mu :$test = none('.', '..')

Returns a list of L<IO::File> and L<IO::Dir> objects for the
files and directories found in the $path. If $path is not given
in lists the entries in the current directory.

A second optional parameter can be given that will be
matched against the strings to filter our certain entries.
By default it filters out the '.' and  the '..'.

Examples:

    for dir() -> $file {
       say $file;
    }

    dir('path/to/directory');

To include all the entries (including . and ..) write:

    dir(test => all())

To include only the entries with .pl extension write

    dir(test => /.pl$/)

=end pod

