=begin pod

=head1 Numeric

    role Numeric { ... }

Common role for numbers and types that can act as numbers.

=head2 Methods

=head3 ACCEPTS

    multi method ACCEPTS(Numeric:D: $other)

Returns True if C<$other> is the same number as the invocant.

=head3 log

    multi sub    log(Numeric:D, Numeric $base = e) returns Numeric:D
    multi method log(Numeric:D: Numeric $base = e) retursn Numeric:D

Calculates the logarithm to base C<$base>. Defaults to the natural logarithm.

=head3 log10

    multi sub    log10(Numeric:D ) returns Numeric:D
    multi method log10(Numeric:D:) returns Numeric:D

Calculates the logarithm to base 10.

=end pod
