=begin pod

=TITLE class Set

    class Set does Setty { }

An immutable set of unique values or objects. These values can be
accessed via the C<{ }> postcircumfix, and always have a value of either
C<True> or C<False>. For a mutable set, see L<SetHash>.

=head1 Methods

=head2 total

    method total(Set:D:)

Equivalent to C<elems>, added for consistency with the L<Bag> and L<Mix>
types

=head1 Operators

=head2 set

    sub set(*@args --> Set)

Creates a C<Set> from the given C<@args>

=head2 (elem)

    multi sub infix:<(elem)>($a, Any $b --> Bool)
    multi sub infix:<(elem)>($a, Set $b --> Bool)

Returns C<True> if the C<Set> C<$b> contains the C<$a> as an element. If
C<$b> is not a C<Set>, it will be coerced to one.

=head2 ∈

    only sub infix:<<"\x2208">>($a, $b --> Bool)

Equivalent to L<(elem)>.

=head2 ∉

    only sub infix:<<"\x2208">>($a, $b --> Bool)

Equivalent to C<!(elem)>, i.e., returns C<True> if the C<Set> C<$b> does
not contain C<$a>.

=head2 (cont)

    multi sub infix:<(cont)>(Any $a, $b --> Bool)
    multi sub infix:<(cont)>(Set $a, $b --> Bool)

Returns C<True> if the C<Set> C<$a> contains C<$b> as an element. If
C<$a> is not a C<Set>, it will be coerced to one.

=head2 ∋

    only sub infix:<<"\x220B">>($a, $b --> Bool)

Equivalent to L<(cont)>.

=head2 ∌

    only sub infix:<<"\x220C">>($a, $b --> Bool)

Equivalent to C<!(cont)>, i.e., returns C<True> if the C<Set> C<$a> does
not contain C<$b>.

=head2 (|)

=head2 ∪

=head2 (&)

=head2 ∩

=head2 (-)

=head2 ∖

=head2 (^)

=head2 ⊖

=head2 (<=)

=head2 ⊆

=head2 ⊈

=head2 (<)

=head2 ⊂

=head2 ⊄

=head2 (>=)

=head2 ⊇

=head2 ⊉

=head2 (>)

=head2 ⊃

=head2 ⊅

=end pod
