=begin pod

=TITLE class Set

    class Set does Setty { }

An immutable set of unique values or objects. These values can be
accessed via the C<{ }> postcircumfix, and always have a value of either
C<True> or C<False>. For a mutable set, see L<SetHash>.

=head1 Methods

=head2 total

    method total(Set:D:)

Equivalent to C<elems>, added for consistency with the L<Bag> and L<Mix>
types

=head1 Operators

=head2 set

    sub set(*@args --> Set)

Creates a C<Set> from the given C<@args>

=head2 infix:<(elem)>

    multi sub infix:<(elem)>($a, Any $b --> Bool)
    multi sub infix:<(elem)>($a, Set $b --> Bool)

Returns C<True> if the C<Set> C<$b> contains the C<$a> as an element. If
C<$b> is not a C<Set>, it will be coerced to one.

=head2 infix:<∈>

    only sub infix:<<"\x2208">>($a, $b --> Bool)

Equivalent to L<(elem)>.

=head2 infix:<∉>

    only sub infix:<<"\x2208">>($a, $b --> Bool)

Equivalent to C<!(elem)>, i.e., returns C<True> if the C<Set> C<$b> does
not contain C<$a>.

=head2 infix:<(cont)>

    multi sub infix:<(cont)>(Any $a, $b --> Bool)
    multi sub infix:<(cont)>(Set $a, $b --> Bool)

Returns C<True> if the C<Set> C<$a> contains C<$b> as an element. If
C<$a> is not a C<Set>, it will be coerced to one.

=head2 infix:<∋>

    only sub infix:<<"\x220B">>($a, $b --> Bool)

Equivalent to L<(cont)>.

=head2 infix:<∌>

    only sub infix:<<"\x220C">>($a, $b --> Bool)

Equivalent to C<!(cont)>, i.e., returns C<True> if the C<Set> C<$a> does
not contain C<$b>.

=head2 infix:<(|)>

    only sub infix:<(|)>(**@p)

Returns the union of all of its arguments. Unless any of its arguments
are L<Baggy>, this creates a new C<Set> that contains all the elements
its arguments contain.

=head2 infix:<∪>

    only sub infix:<<"\x222A">>(|p)

Equivalent to L<(|)>.

=head2 infix:<(&)>

    only sub infix:<(&)>(**@p)

Returns the intersection of all of its arguments. Unless any of its
arguments are L<Baggy>, this creates a new C<Set> that contains only the
elements that all of its arguments contain.

=head2 infix:<∩>

    only sub infix:<<"\x2229">>(|p)

Equivalent to L<(&)>.

=head2 infix:<(-)>

    only sub infix:<(-)>(**@p)

Unless the first argument is L<Baggy>, returns the C<Set> made up all
the elements the first argument has but the rest don't, i.e., of all the
elements of the first argument, minus the elements from the other
arguments.

=head2 infix:<∖>

    only sub infix:<<"\x2216">>(|p)

Equivalent to L<(-)>.

=head2 infix:<(^)>

    multi sub infix:<(^)>(Any $a, Any $b --> Setty)
    multi sub infix:<(^)>(Set $a, Set $b --> Setty)

Returns the C<Set> made up of all the elements that $a has but $b
doesn't and all the elements $b has but $a doesn't. Equivalent to
C<($a ∖ $b) ∪ ($b ∖ $a)>.

=head2 infix:<⊖>

    only sub infix:<<"\x2296">>($a, $b --> Setty)

Equivalent to L<(^)>

=head2 infix:<(<=)>

=head2 infix:<⊆>

=head2 infix:<⊈>

=head2 infix:<(<)>

=head2 infix:<⊂>

=head2 infix:<⊄>

=head2 infix:<(>=)>

=head2 infix:<⊇>

=head2 infix:<⊉>

=head2 infix:<(>)>

=head2 infix:<⊃>

=head2 infix:<⊅>

=end pod
