=begin pod

=TITLE role Setty

    class Setty does QuantHash { }

A role for collections of unique objects. See L<Set> and L<SetHash>.

=head1 Methods

=head2 grab

=head2 grabpairs

=head2 pick

=head2 roll

=head2 keys

=head2 values

=head2 kv

=head2 elems

=head2 total

=head2 new-fp

=head2 ACCEPTS

=end pod
