=begin pod

=TITLE class Signature

    class Signature { ... }

A signature is a static description of the parameter list of a code object.
That is, it describes what and how many arguments you need to pass to it
for invocation.

Passing arguments to a signature I<binds> the arguments the parameters,
and loosly speaken to the signature.

=head1 Methods

=head2 params

    method params(Signature:D:) returns Positional

Returns the list of L<Parameter> objects that make up the signature.

=head2 arity

    method arity(Signature:D:) returns Int:D

Returns the minimal number of positional arguments required to satisfy
the signature.

=head2 count

    method count(Signature:D:) returns Real:D

Returns the maximal number of positional arguments which can be bound
to the signature. Returns C<Inf> if there a positional parameter is slurpy.

=end pod
