=begin pod

=TITLE class Any

=SUBTITLE Thing/object

    class Any is Mu { ... }

While L<Mu|/type/Mu> is the root of the Perl 6 class hierarchy, C<Any> is the class
that serves as a default base class for new classes, and as the base class for
most built-in classes.

Since Perl 6 intentionally confuses items and single-element lists, most
methods in C<Any> are also present on class L<List|/type/List>, and coerce to
List or a list-like type.

=head1 Methods

=head2 method ACCEPTS

    multi method ACCEPTS(Any:D: Mu $other)

Returns C<True> if C<$other === self> (i.e. it checks object identity).

=head2 method any

Interprets the invocant as a list and creates an C<any>-Junction from it.

=head2 method all

Interprets the invocant as a list and creates an C<all>-Junction from it.

=head2 method one

Interprets the invocant as a list and creates an C<one>-Junction from it.

=head2 method none

Interprets the invocant as a list and creates an C<none>-Junction from it.

=head2 method list

Interprets the invocant as a list, and returns that list.

=head2 method flat

Interprets the invocant as a list, flattens it, and returns that list.

    say ((1, 2), (3)).elems;        # 2
    say ((1, 2), (3)).flat.elems;   # 3

=head2 method eager

Interprets the invocant as a list, evaluates it eagerly, and returns that
list.

=head2 method elems

Interprets the invocant as a list, and returns the number of elements in the
list.

=head2 method end

Interprets the invocant as a list, and returns the last index of that list.

=end pod
