=begin pod

=TITLE role Baggy

    class Baggy does QuantHash { }

A role for collections of weighted objects. See L<Bag>, L<BagHash>, and
L<Mixy>.

=head1 Methods

=head2 grab

=head2 grabpairs

=head2 pick

=head2 pickpairs

=head2 roll

=head2 classify-list

=head2 categorize-list

=head2 keys

=head2 values

=head2 kv

=head2 elems

=head2 total

=head2 new-fp

=head2 ACCEPTS

=end pod
