=begin pod

=TITLE role Blob

=SUBTITLE Common interface for binary large objects

    role Blob[::T = uint8] does Positional[T] does Stringy { }

The C<Blob> role is an immutable interface to binary types, and offers a
list-like interface to lists of integers, typically unsigned integers.

=head1 Methods

=head2 method new

    method new(*@codes)

Creates a C<Blob> from a list of integers.

=head2 method  Bool

    multi method Bool(Blob:D:)

Returns C<False> if and only if the buffer is empty.

=head2 method elems

    multi method elems(Blob:D:) returns Int:D

Returns the number of elements of the buffer.

=head2 method decode

    multi method decode(Blob:D: Str:D $encoding = 'UTF-8') returns Str:D

Applies an encoding to turn the blob into a L<Str|/type/Str>.

=head2 method subbuf

    method subbuf(Int $from, Int $len = self.elems) returns Blob:D

Extracts a part of the invocant buffer, starting from the index with
elements C<$from>, and taking C<$len> elements (or less if the buffer is
shorter), and creates a new buffer as the result.

    say Blob.new(1..10).subbuf(2, 4);    # Blob:0x<03 04 05 06>

=end pod
