=begin pod

=TITLE role IO

=SUBTITLE Tag role for all input/output types

    role IO { }

The IO role provides no functionality itself, and moreso just marks if a
particular object relates to input/output.

=head1 Operators

=head2 method prompt

    sub prompt($msg)

Prints C<$msg> to the standard output and waits
for the user to type in something and finish with an ENTER.
Returns the string typed in without the trailing newline.

    my $name = prompt("Hi, what's your name? ");

=head2 method dir

    sub dir(Cool $path = '.', Mu :$test = none('.', '..'))

Returns a list of L<IO::File> and L<IO::Path> objects for the
files and directories found in the $path. If $path is not given
assumes the current directory.

A second optional parameter can be given that will be
matched against the strings to filter out certain entries.
By default it filters out the '.' and '..' entries.

Examples:

    for dir() -> $file {
       say $file;
    }

    dir('path/to/directory');

To include all the entries (including . and ..) write:

    dir(test => all())

To include only entries with a .pl extension write:

    dir(test => /.pl$/)

TODO: more IO Ops

=end pod
