=begin pod

=TITLE class Nil

    class Nil is Iterator { }

Represents an empty list in list context, and an undefined value in item
context.


=head1 Methods

=head2 gist

    method gist() returns Str:D

Returns C<"Nil">

=head2 Str

    method Str() returns Str:D

Returns the empty string.

=end pod
