=begin pod

=TITLE class Set

    class Set does Setty { }

An immutable set of unique values or objects. These values can be
accessed via the C<{ }> postcircumfix, and always have a value of either
C<True> or C<False>. For a mutable set, see L<SetHash>.

=head1 Methods

=head2 total

    method total(Set:D:)

Equivalent to C<elems>, added for consistency with the L<Bag> and L<Mix>
types

=head1 Operators

All of the following infix operators will take most types as their
arguments and coerce them to C<Set>s. In some cases, if a type of an
argument is a L<Bag>, the infix operator will behave in a different but
analogous way to the one described here.

=head2 sub set

    sub set(*@args --> Set)

Creates a C<Set> from the given C<@args>

=head2 infix (elem)

    multi sub infix:<(elem)>($a, Any $b --> Bool)
    multi sub infix:<(elem)>($a, Set $b --> Bool)

Returns C<True> if the C<Set> C<$b> contains the C<$a> as an element. If
C<$b> is not a C<Set>, it will be coerced to one.

=head2 infix ∈

    only sub infix:<<"\x2208">>($a, $b --> Bool)

Equivalent to L«#infix (elem)».

=head2 infix ∉

    only sub infix:<<"\x2208">>($a, $b --> Bool)

Equivalent to C<!(elem)>, i.e., returns C<True> if the C<Set> C<$b> does
not contain C<$a>.

=head2 infix (cont)

    multi sub infix:<(cont)>(Any $a, $b --> Bool)
    multi sub infix:<(cont)>(Set $a, $b --> Bool)

Returns C<True> if the C<Set> C<$a> contains C<$b> as an element. If
C<$a> is not a C<Set>, it will be coerced to one.

=head2 infix ∋

    only sub infix:<<"\x220B">>($a, $b --> Bool)

Equivalent to L«#infix (cont)».

=head2 infix ∌

    only sub infix:<<"\x220C">>($a, $b --> Bool)

Equivalent to C<!(cont)>, i.e., returns C<True> if the C<Set> C<$a> does
not contain C<$b>.

=head2 infix (|)

    only sub infix:<(|)>(**@p)

Returns the union of all of its arguments. Unless any of its arguments
are L<Baggy>, this creates a new C<Set> that contains all the elements
its arguments contain.

=head2 infix ∪

    only sub infix:<<"\x222A">>(|p)

Equivalent to L«#infix (V<|>)».

=head2 infix (&)

    only sub infix:<(&)>(**@p)

Returns the intersection of all of its arguments. Unless any of its
arguments are L<Baggy>, this creates a new C<Set> that contains only the
elements that all of its arguments contain.

=head2 infix ∩

    only sub infix:<<"\x2229">>(|p)

Equivalent to L«#infix (&)».

=head2 infix (-)

    only sub infix:<(-)>(**@p)

Unless the first argument is L<Baggy>, returns the C<Set> made up all
the elements the first argument has but the rest don't, i.e., of all the
elements of the first argument, minus the elements from the other
arguments.

=head2 infix ∖

    only sub infix:<<"\x2216">>(|p)

Equivalent to L«#infix (-)».

=head2 infix (^)

    multi sub infix:<(^)>(Any $a, Any $b --> Setty)
    multi sub infix:<(^)>(Set $a, Set $b --> Setty)

Returns the C<Set> made up of all the elements that C<$a> has but C<$b>
doesn't and all the elements C<$b> has but C<$a> doesn't. Equivalent to
C<($a ∖ $b) ∪ ($b ∖ $a)>.

=head2 infix ⊖

    only sub infix:<<"\x2296">>($a, $b --> Setty)

Equivalent to L«#infix (^)»

=head2 infix (<=)

    multi sub infix:<<(<=)>>(Any $a, Any $b --> Bool)
    multi sub infix:<<(<=)>>(Setty $a, Setty $b --> Bool)

Returns C<True> if C<$a> is a subset or is equal to C<$b>, i.e., if all the
elements of C<$a> are elements of C<$b>, and C<$a> is a smaller or equal
sized set than C<$b>.

=head2 infix ⊆

    only sub infix:<<"\x2286">>($a, $b --> Bool)

Equivalent to L«#infix (<=)».

=head2 infix ⊈

    only sub infix:<<"\x2288">>($a, $b --> Bool)

Equivalent to C«!(<=)».

=head2 infix (<)

    multi sub infix:<<(<)>>(Any $a, Any $b --> Bool)
    multi sub infix:<<(<)>>(Setty $a, Setty $b --> Bool)

Returns C<True> if C<$a> is a strict subset of C<$b>, i.e., that all the
elements of C<$a> are elements of C<$b>, but C<$a> is a smaller set than
C<$b>.

=head2 infix ⊂

    only sub infix:<<"\x2282">>($a, $b --> Bool)

Equivalent to L«#infix (<)».

=head2 infix ⊄

    only sub infix:<<"\x2284">>($a, $b --> Bool)

Equivalent to C«!(<)».

=head2 infix (>=)

    multi sub infix:<<(>=)>>(Any $a, Any $b --> Bool)
    multi sub infix:<<(>=)>>(Setty $a, Setty $b --> Bool)

Like L«#infix (<=)» with reversed arguments. Returns C<True> if C<$b>
is a subset of or equal to C<$a>.

=head2 infix ⊇

    only sub infix:<<"\x2287">>($a, $b --> Bool)

Equivalent to L«#infix (>=)».

=head2 infix ⊉

    only sub infix:<<"\x2289">>($a, $b --> Bool)

Equivalent to C«!(>=)».

=head2 infix (>)

    multi sub infix:<<(>)>>(Any $a, Any $b --> Bool)
    multi sub infix:<<(>)>>(Setty $a, Setty $b --> Bool)

Like L«#infix (<)» with reversed arguments. Returns C<True> if C<$b>
is a strict subset of C<$a>.

=head2 infix ⊃

    only sub infix:<<"\x2283">>($a, $b --> Bool)

Equivalent to L«#infix (>)».

=head2 infix ⊅

    only sub infix:<<"\x2285">>($a, $b --> Bool)

Equivalent to C«!(>)».

=end pod
