=begin pod

=TITLE class X::Proc::Async::OpenForWriting

=SUBTITLE Error due to writing to a read-only L<Proc::Async> object

    class X::Proc::Async::OpenForWriting is Exception { ... }

When a L<Proc::Async> object is opened only for reading from the external
program (no C<:w> passed to open), and a write operation such as C<write>,
C<print> and C<say> is performed, an exception of type
X<X::Proc::Async::OpenForWriting> is thrown:

    my $proc = Proc::Async.new("echo");
    $proc.start;
    $proc.say(42)   # Process must be opened for writing with :w to call 'say'

=head1 Methods

=head2 method method

    method method(X::Proc::Async::OpenForWriting:D:)

Returns the method name that was called and which caused the exception.

=end pod
