=begin pod

=TITLE class X::Syntax::Augment::Role

=SUBTITLE Compilation error due to augmenting a role

    class X::Syntax::Augment::Role does X::Syntax { }

Compile time error thrown when trying to augment a role.

For example

    use MONKEY-TYPING;
    augment role Positional { }

dies with

    ===SORRY!===
    Cannot augment role Positional, since roles are immutable

=head1 Methods

=head2 method role-name

    method role-name() returns Str:D

Returns the name of the role that was attempted to augment.

=end pod
