=begin pod

=TITLE class Backtrace::Frame

=SUBTITLE Single frame of a L<Backtrace>

    class Backtrace::Frame { }

A single backtrace frame. It identifies a location in the source code.

=head1 Methods

=head2 method file

Defined as:

    method file(Backtrace::Frame:D) returns Str

Usage:

    FRAME.file

Returns the file name.

=head2 method line

Defined as:

    method line(Backtrace::Frame:D) returns Int

Usage:

    FRAME.line

Returns the line number (line numbers start to count from 1).

=head2 method code

Defined as:

    method code(Backtrace::Frame:D)

Usage:

    FRAME.code

Returns the code object into which C<.file> and C<.line> point, if available.

=head2 method subname

Defined as:

    method subname(Backtrace::Frame:D) returns Str

Usage:

    FRAME.subname

Returns the name of the enclosing subroutine.

=head2 method is-hidden

Defined as:

    method is-hidden(Backtrace::Frame:D) return Bool:D

Usage:

    FRAME.is-hidden

Returns C<True> if the frame is marked as hidden with the
C<is hidden-from-backtrace> trait.

=head2 method is-routine

Defined as:

    method is-routine(Backtrace::Frame:D) return Bool:D

Usage:

    FRAME.is-routine

Return C<True> if the frame point into a routine (and not
into a mere L<Block>).

=head2 method is-setting

Defined as:

    method is-setting(Backtrace::Frame:D) return Bool:D

Usage:

    FRAME.is-setting

Returns C<True> if the frame is part of a setting.

=end pod
