=begin pod

=TITLE class Pod::Block::Named

=SUBTITLE Named block in a Pod document

    class Pod::Block::Named is Pod::Block { }

Class for a named Pod block. For example

    =begin mysection
    ...
    =end mysection

creates a C<Pod::Block::Named> with name C<mysection>.

=head1 Methods

=head2 method name

    method name() returns Str:D

Returns the name of the block.

=end pod
