=begin pod

=TITLE Meta-Object Protocol

TODO

=head1 Metamethods

TODO

=head2 X<WHAT|syntax,WHAT>

The type object of the type.

=head2 X<WHICH|syntax,WHICH>

The object's identity value.

=head2 X<WHO|syntax,WHO>

The package supporting the object.

=head2 X<WHERE|syntax,WHERE>

The memory address of the object.

=head2 X<HOW|syntax,HOW>

The metaclass object: "Higher Order Workings"

=head2 X<WHY|syntax,WHY>

The attached Pod value.

=head2 X<DEFINITE|syntax,DEFINITE>

The object has a valid concrete representation.

=head2 X<VAR|syntax,VAR>

Returns the underlying C<Scalar> object, if there is one.

=end pod
